spring:
  datasource:
    url: jdbc:mysql://192.168.3.201:3306/organization?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: password
    initialization-mode: always